version: "3"

services:
  core:
    container_name: app
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    environment:
      INIT_MODEL: False
    networks:
      - app-framework
    volumes:
      - ./generated_resources:/generated_resources
    healthcheck:
      test: [ "CMD", "curl", "-f", "-X", "GET", "http://localhost:80/api/v1/health/check" ]
      interval: 300s
      timeout: 180s
      retries: 5

networks:
  app-framework:
    name: app-framework